# permissions to do viewer swarms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: swarm-viewer-role
rules:
- apiGroups:
  - experiments.mad.md
  resources:
  - swarms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - experiments.mad.md
  resources:
  - swarms/status
  verbs:
  - get
